name: ct484_project
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flex_color_scheme: ^8.1.1
  flutter_switch: ^0.3.2
  flutter_dotenv: ^5.2.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  image_picker: ^1.1.2
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.2
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
    